# Build the docker image
docker build -t simpleidserver -f Dockerfile-Authorization .
docker build -t uma -f Dockerfile-Uma .
docker build -t websiteapi -f Dockerfile-WebSiteApi .
docker build -t website -f Dockerfile-WebSite .
docker build -t configuration -f Docker-Configuration .
docker build -t simpleidserver -f Dockerfile-Authorization-Https .
docker build -t marketing -f Dockerfile-Marketing .

# delete all images
docker rm -f $(docker ps -aq)
docker rmi simpleidentityserverdocker_websiteapi
docker rmi simpleidentityserverdocker_simpleidserver
docker rmi simpleidentityserverdocker_configuration
docker rmi simpleidentityserverdocker_website
docker rmi simpleidentityserverdocker_uma
docker rmi simpleidentityserverdocker_manager

# Run postgresql
docker run --name postgresql -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=postgres -d postgres

# Run simpleidserver
docker run --name simpleidserver -e DB_ALIAS=postgresql -e DB_PORT=5432 -p 5443:5443 -p 5000:5000 --link postgresql -it simpleidserver /bin/bash

# Run postgresql - uma
docker run --name postgresql_uma -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=postgres -d postgres

# Run UMA
docker run --name uma -e DB_ALIAS=postgresql -e DB_PORT=5432 --link postgresql_uma:postgresql --link simpleidserver:simpleidserver uma

# Run mongo db
docker run --name mongo -d mongo

# Run application
docker run --name websiteapi --link mongo:mongo -d websiteapi

# Export certificate
openssl x509 -inform der -in LokitCa.cer -out LokitCa.pem

REM run website
docker run -d -e FORCE_SSL=yes -e SSL_CERT="-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAv2tMQQBZOd3Kf4jOJbwpTanrM9TUUox6Yi4D+RhCxlLEMHCq\nVcSb3+3xkbMzk45GwckNMZZIqBMRMG3xm670I8fqBy8SIqmkb8K7Fw/XepfDd3PP\nd5ox4SRa92w9ZNgDjZGM/gBVo/rUR0696ebznl+envYu755VMrXBq87ZqrTos+tU\nC2ij0NNXRxBpBW90sNW2OfxZUb/ggSUGE154RCNjwyjRpcptqQPZYFukII/n9Tzu\nQStYIQVFLYtPHi4vOofw0YvSKKdL/J/VzYiRs62VXbo6bSdX2uncifa8BfhHPxMe\nVzjrgbG/hQIXFlC/APHodUREoQ6a/RnrZY9F2wIDAQABAoIBAA5iS2q10ktt/LAx\nTguTRGewuI4x1IcKRY07viwWMOv2C5/eORaH1yfwTLV+CbnXuHGjoE+usz5m0suL\n8qdk8eiZNnjpH+VytpR4knyzQb+iSHU6wrpokyeP07W0lwQNOjsfPSdX5bEt57/r\nmiUwJ/QpmEhQR74IbLuKR+4XdZwFQ1kkaTYnvoEPWML6PEAfZKs2Ql5XUEWJoN06\nt1Ycs3P5JzWDJJbUGUAWQk2dBoetiiKbTmyfVzAHFDp5Elj0tNg3NO3LeS4Cysew\nnwrpXPw8xjY83Y/lXXE5RW6ENOIC4/uflBWbbx9ymixUAd1SnALv11l9s3+QOZJ6\noh7PC9ECgYEAysVxXQT1NSktBX93U+ZBdIBFm//G5vTJBa78DIGGQduVzbo8z4jO\n4atq3aa3s+I3zgoq+OgIP9+nHjgOw8Ol8COTPeLF8lluh1/Hjr4LUQlB4IPhQl7h\nBVKJWycw3xjYoxKJklNzUzgiLsnoZeT2fzOemkfuenrnVjK8VKOBNDECgYEA8ar5\nPf/Ip7IJ1ZYO98DwDEqBjwRq97ZNUVlo+7BrQMkYZutcm7ayUdaQLDdZWzwG/Iun\nSGJVrcJ8C2vAsVyxIDCd++lPNtxb+fqt1PYsXg/eDPNt8lhIAoVzG3FgyvHIW3BX\nLipmPGdEiD7kviffSYU7m2qwFvH2HfgwLTxfU8sCgYEAkcbY9VL3JrzvjSBSnZLQ\nQ/1kDf8Y9DnPu7JNqoAEEZzYWgsmZN2qPjuKnMebEkv0asCMnF3UcHdOIj+S/dLO\nnZI17Sv3u3/oIpMNWOXwJNZO8iZd7+VeSQFJlqraS8oFFVfiZ7xvEMkuagzmczrk\nrBZkU+6a2Js7bZEULJVP8kECgYAJ55X7goY4yUU56cKHSPMNregNcoLn0CLvGJkC\n58Idj6BeZ3sOLri0PfT+uu4AnT80Do02nEEis/vdg/cLzd68kQGIl5FVkEZ8wldp\niQVcfY3+PePdsNySreF/2G+9IZeyl7IbBEXYZ+sZImrBmGTAYKOGxSKebiBGLivb\nTsQhbQKBgFZlScgMXgEorNa61UFWGcVRCthdhTPDytgbC7XKQRax4eqOzTGGCup5\n8rDK8+hD7nRoOcbDYkMKs2ZLZ21MUN3rAq8FR+Oyl3ZeR1MGroHsel9Juas4iX/p\nDZRi6oXqwEuQc6pMkKLwk0zqrRI6KbsdXh4q8nHxMs6Hzw3A7dAM\n-----END RSA PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIIDXjCCAkqgAwIBAgIQox5aTcOsprtJS/zAbKBcPjAJBgUrDgMCHQUAMDIxDDAK\nBgNVBAsTA0RldjEPMA0GA1UEChMGQWR2SUNUMREwDwYDVQQDEwhMb2tpdCBDQTAe\nFw0xNjA2MjgxNzU0MDNaFw0zOTEyMzEyMzU5NTlaMDIxDDAKBgNVBAsTA0RldjEP\nMA0GA1UEChMGQWR2SUNUMREwDwYDVQQDEwhMb2tpdCBDQTCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBAL9rTEEAWTndyn+IziW8KU2p6zPU1FKMemIuA/kY\nQsZSxDBwqlXEm9/t8ZGzM5OORsHJDTGWSKgTETBt8Zuu9CPH6gcvEiKppG/CuxcP\n13qXw3dzz3eaMeEkWvdsPWTYA42RjP4AVaP61EdOvenm855fnp72Lu+eVTK1wavO\n2aq06LPrVAtoo9DTV0cQaQVvdLDVtjn8WVG/4IElBhNeeEQjY8Mo0aXKbakD2WBb\npCCP5/U87kErWCEFRS2LTx4uLzqH8NGL0iinS/yf1c2IkbOtlV26Om0nV9rp3In2\nvAX4Rz8THlc464Gxv4UCFxZQvwDx6HVERKEOmv0Z62WPRdsCAwEAAaN4MHYwDwYD\nVR0TAQH/BAUwAwEB/zBjBgNVHQEEXDBagBAh73KWFFRoD18cF9c1q5CqoTQwMjEM\nMAoGA1UECxMDRGV2MQ8wDQYDVQQKEwZBZHZJQ1QxETAPBgNVBAMTCExva2l0IENB\nghCjHlpNw6ymu0lL/MBsoFw+MAkGBSsOAwIdBQADggEBAAYxRuSBvmPYkVYYOGeI\nH6NItgbHOMoMal3/RCEJ9cisoIw0yQOGKD2m8I8IuuSkV9GnYpFXIjN4ALNXdqPq\n5XjkhxAd73nkOZHMWd5RWYKqxM+gTPP9+MoPJak6Y0Mfmla31rzySG5eEaBlk79O\nic58spT7Et9DESfdx9At3hgJG703dEbaukkN2BDumowfEobzVbl9QacydcmeNPOc\n8FqR13dRjdgDhV3gsLKtJIMdg2l1eyqWw/qtJk+PNTRnr3pi5aueyl3huWEOpCeB\noAaUR4A4KYIxnS+umBo2zVOzyTE2r/leYpF3VomVgyzZx7Sp7qbaIKwLZSRS5AVW\nxvU=\n-----END CERTIFICATE-----\n" --name website simpleidentityserverdocker_website
docker run -d --link website:website -p 443:443 dockercloud/haproxy

REM simpleidserver
docker run --name postgresql -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=postgres -d postgres
docker run --name simpleidserver -e DB_ALIAS=postgresql -e DB_PORT=5432 -e FORCE_SSL=yes -e SSL_CERT="-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAv2tMQQBZOd3Kf4jOJbwpTanrM9TUUox6Yi4D+RhCxlLEMHCq\nVcSb3+3xkbMzk45GwckNMZZIqBMRMG3xm670I8fqBy8SIqmkb8K7Fw/XepfDd3PP\nd5ox4SRa92w9ZNgDjZGM/gBVo/rUR0696ebznl+envYu755VMrXBq87ZqrTos+tU\nC2ij0NNXRxBpBW90sNW2OfxZUb/ggSUGE154RCNjwyjRpcptqQPZYFukII/n9Tzu\nQStYIQVFLYtPHi4vOofw0YvSKKdL/J/VzYiRs62VXbo6bSdX2uncifa8BfhHPxMe\nVzjrgbG/hQIXFlC/APHodUREoQ6a/RnrZY9F2wIDAQABAoIBAA5iS2q10ktt/LAx\nTguTRGewuI4x1IcKRY07viwWMOv2C5/eORaH1yfwTLV+CbnXuHGjoE+usz5m0suL\n8qdk8eiZNnjpH+VytpR4knyzQb+iSHU6wrpokyeP07W0lwQNOjsfPSdX5bEt57/r\nmiUwJ/QpmEhQR74IbLuKR+4XdZwFQ1kkaTYnvoEPWML6PEAfZKs2Ql5XUEWJoN06\nt1Ycs3P5JzWDJJbUGUAWQk2dBoetiiKbTmyfVzAHFDp5Elj0tNg3NO3LeS4Cysew\nnwrpXPw8xjY83Y/lXXE5RW6ENOIC4/uflBWbbx9ymixUAd1SnALv11l9s3+QOZJ6\noh7PC9ECgYEAysVxXQT1NSktBX93U+ZBdIBFm//G5vTJBa78DIGGQduVzbo8z4jO\n4atq3aa3s+I3zgoq+OgIP9+nHjgOw8Ol8COTPeLF8lluh1/Hjr4LUQlB4IPhQl7h\nBVKJWycw3xjYoxKJklNzUzgiLsnoZeT2fzOemkfuenrnVjK8VKOBNDECgYEA8ar5\nPf/Ip7IJ1ZYO98DwDEqBjwRq97ZNUVlo+7BrQMkYZutcm7ayUdaQLDdZWzwG/Iun\nSGJVrcJ8C2vAsVyxIDCd++lPNtxb+fqt1PYsXg/eDPNt8lhIAoVzG3FgyvHIW3BX\nLipmPGdEiD7kviffSYU7m2qwFvH2HfgwLTxfU8sCgYEAkcbY9VL3JrzvjSBSnZLQ\nQ/1kDf8Y9DnPu7JNqoAEEZzYWgsmZN2qPjuKnMebEkv0asCMnF3UcHdOIj+S/dLO\nnZI17Sv3u3/oIpMNWOXwJNZO8iZd7+VeSQFJlqraS8oFFVfiZ7xvEMkuagzmczrk\nrBZkU+6a2Js7bZEULJVP8kECgYAJ55X7goY4yUU56cKHSPMNregNcoLn0CLvGJkC\n58Idj6BeZ3sOLri0PfT+uu4AnT80Do02nEEis/vdg/cLzd68kQGIl5FVkEZ8wldp\niQVcfY3+PePdsNySreF/2G+9IZeyl7IbBEXYZ+sZImrBmGTAYKOGxSKebiBGLivb\nTsQhbQKBgFZlScgMXgEorNa61UFWGcVRCthdhTPDytgbC7XKQRax4eqOzTGGCup5\n8rDK8+hD7nRoOcbDYkMKs2ZLZ21MUN3rAq8FR+Oyl3ZeR1MGroHsel9Juas4iX/p\nDZRi6oXqwEuQc6pMkKLwk0zqrRI6KbsdXh4q8nHxMs6Hzw3A7dAM\n-----END RSA PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIIDXjCCAkqgAwIBAgIQox5aTcOsprtJS/zAbKBcPjAJBgUrDgMCHQUAMDIxDDAK\nBgNVBAsTA0RldjEPMA0GA1UEChMGQWR2SUNUMREwDwYDVQQDEwhMb2tpdCBDQTAe\nFw0xNjA2MjgxNzU0MDNaFw0zOTEyMzEyMzU5NTlaMDIxDDAKBgNVBAsTA0RldjEP\nMA0GA1UEChMGQWR2SUNUMREwDwYDVQQDEwhMb2tpdCBDQTCCASIwDQYJKoZIhvcN\nAQEBBQADggEPADCCAQoCggEBAL9rTEEAWTndyn+IziW8KU2p6zPU1FKMemIuA/kY\nQsZSxDBwqlXEm9/t8ZGzM5OORsHJDTGWSKgTETBt8Zuu9CPH6gcvEiKppG/CuxcP\n13qXw3dzz3eaMeEkWvdsPWTYA42RjP4AVaP61EdOvenm855fnp72Lu+eVTK1wavO\n2aq06LPrVAtoo9DTV0cQaQVvdLDVtjn8WVG/4IElBhNeeEQjY8Mo0aXKbakD2WBb\npCCP5/U87kErWCEFRS2LTx4uLzqH8NGL0iinS/yf1c2IkbOtlV26Om0nV9rp3In2\nvAX4Rz8THlc464Gxv4UCFxZQvwDx6HVERKEOmv0Z62WPRdsCAwEAAaN4MHYwDwYD\nVR0TAQH/BAUwAwEB/zBjBgNVHQEEXDBagBAh73KWFFRoD18cF9c1q5CqoTQwMjEM\nMAoGA1UECxMDRGV2MQ8wDQYDVQQKEwZBZHZJQ1QxETAPBgNVBAMTCExva2l0IENB\nghCjHlpNw6ymu0lL/MBsoFw+MAkGBSsOAwIdBQADggEBAAYxRuSBvmPYkVYYOGeI\nH6NItgbHOMoMal3/RCEJ9cisoIw0yQOGKD2m8I8IuuSkV9GnYpFXIjN4ALNXdqPq\n5XjkhxAd73nkOZHMWd5RWYKqxM+gTPP9+MoPJak6Y0Mfmla31rzySG5eEaBlk79O\nic58spT7Et9DESfdx9At3hgJG703dEbaukkN2BDumowfEobzVbl9QacydcmeNPOc\n8FqR13dRjdgDhV3gsLKtJIMdg2l1eyqWw/qtJk+PNTRnr3pi5aueyl3huWEOpCeB\noAaUR4A4KYIxnS+umBo2zVOzyTE2r/leYpF3VomVgyzZx7Sp7qbaIKwLZSRS5AVW\nxvU=\n-----END CERTIFICATE-----\n" --link postgresql -d simpleidentityserverdocker_simpleidserver
docker run -d --link simpleidserver:simpleidserver -p 5443:443 dockercloud/haproxy