FROM microsoft/dotnet:latest

ENV ASPNETCORE_ENVIRONMENT docker
ENV DB_ALIAS postgresql
ENV DB_PORT 5432
ENV DATA_MIGRATED true

COPY SimpleIdentityServer/SimpleIdentityServer/src /app

WORKDIR /app

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
	&& echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list \
	&& echo "deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list \
	&& echo "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list \
	&& apt-get update \
	&& apt-get install -y mono-devel
RUN sed -i 's/\r//' /app/idserver-configuration-entrypoint.sh
RUN sed -i 's/\r//' /app/wait-for-it.sh
RUN chmod +x /app/idserver-configuration-entrypoint.sh && chmod +x /app/wait-for-it.sh
RUN dotnet restore

ENTRYPOINT ["/app/idserver-configuration-entrypoint.sh"]