FROM microsoft/dotnet:latest

ENV ASPNETCORE_ENVIRONMENT docker
ENV DB_ALIAS postgresql
ENV DB_PORT 5432

COPY SimpleIdentityServer/SimpleIdentityServer/src /app

WORKDIR /app

RUN apt-get update -y && \
    apt-get install ca-certificates -y
ADD LokitCA.crt /usr/local/share/ca-certificates/LokitCA.crt
RUN update-ca-certificates --verbose
RUN sed -i 's/\r//' /app/simpleidserver-entrypoint.sh
RUN sed -i 's/\r//' /app/wait-for-it.sh
RUN chmod +x /app/simpleidserver-entrypoint.sh && chmod +x /app/wait-for-it.sh
RUN dotnet restore

EXPOSE 5443

# ENTRYPOINT ["/app/simpleidserver-entrypoint.sh"]