FROM microsoft/dotnet:latest

ENV ASPNETCORE_ENVIRONMENT docker
ENV DB_ALIAS postgresql
ENV DB_PORT 5432

COPY SimpleIdentityServer/SimpleIdentityServer/src /app

WORKDIR /app

RUN sed -i 's/\r//' /app/simpleidserver-entrypoint.sh
RUN sed -i 's/\r//' /app/wait-for-it.sh
RUN chmod +x /app/simpleidserver-entrypoint.sh && chmod +x /app/wait-for-it.sh
RUN dotnet restore

EXPOSE 5000

ENTRYPOINT ["/app/simpleidserver-entrypoint.sh"]